server:
  port: 8999

spring:
  application:
    name: api-gateway

eureka:
  instance:
    hostname: localhost

cloud:
  gateway:
    routes:
      - id: user-service
        uri: lb://user-service
        predicates:
          - Path=/user/**

      - id: contact-service
        uri: lb://contact-service
        predicates:
          - Path=/contact/**